server:
  port: 7071
spring:
  application:
    name: sc-eureka-client1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/
    preferSameZoneEureka:
      instance: true
    metadataMap:
      zone: zone_client0

