logging:
  level:
    root: "debug"
server:
  port: 9201
service-url:
  sb-service: http://localhost:8080
spring:
  cloud:
    gateway:
      routes:
        - id: sb #路由的ID
          uri: ${service-url.sb-service}/t/echo
          predicates: # 断言，路径相匹配的进行路由
            - Path=/t/echo
          filters:
            - name: CircuitBreaker
              args:
                name: fallbackCircuitBreaker
                fallbackUri: forward:/fallback